
server:
  port: 7070
  
spring:
  h2:
    console:
      enabled: true
  #jpa:
   # hibernate:
    #  ddl-auto: validate
    #show-sql: true
    #properties:
     # hibernate:
      #  dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: warn
    com.example.demo: warn
#  file: logs/dev.log
  

